import {
  Activity,
  AlignLeft,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Award,
  Bell,
  Bold,
  Book,
  Bookmark,
  Building2,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleCheck,
  CircleDot,
  CircleX,
  Clock,
  Code,
  CodeXml,
  Contrast,
  Copy,
  Cpu,
  Database,
  Download,
  Ellipsis,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Flag,
  Flame,
  Folder,
  Gauge,
  GitBranch,
  GraduationCap,
  History,
  Image as ImageIcon,
  Info,
  Italic,
  Key,
  LayoutGrid,
  Lightbulb,
  List,
  ListOrdered,
  Lock,
  Mail,
  Map as MapIcon,
  MapPin,
  Maximize,
  Menu,
  MessageCircle,
  Minus,
  Monitor,
  Moon,
  PanelLeft,
  PanelRight,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Search,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  Shuffle,
  Sigma,
  SlidersHorizontal,
  SquareTerminal,
  Star,
  Sun,
  Table,
  Tag,
  Target,
  Terminal,
  Timer,
  Trophy,
  TriangleAlert,
  Upload,
  User,
  Users,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/** Lucide icons. Rendered on a 24×24 grid, typically at 16–18px. */
const icons = {
  code: Code,
  codeXml: CodeXml,
  search: Search,
  bell: Bell,
  moon: Moon,
  sun: Sun,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  check: Check,
  checkCircle: CircleCheck,
  xCircle: CircleX,
  circle: Circle,
  circleDot: CircleDot,
  circleHalf: Contrast,
  x: X,
  plus: Plus,
  minus: Minus,
  play: Play,
  upload: Upload,
  terminal: Terminal,
  terminalSquare: SquareTerminal,
  tag: Tag,
  building: Building2,
  shuffle: Shuffle,
  target: Target,
  flame: Flame,
  trophy: Trophy,
  clock: Clock,
  timer: Timer,
  eye: Eye,
  eyeOff: EyeOff,
  refresh: RefreshCw,
  copy: Copy,
  share: Share2,
  bookmark: Bookmark,
  book: Book,
  bulb: Lightbulb,
  settings: Settings,
  sliders: SlidersHorizontal,
  grid: LayoutGrid,
  file: FileText,
  users: Users,
  user: User,
  activity: Activity,
  monitor: Monitor,
  cpu: Cpu,
  gauge: Gauge,
  history: History,
  download: Download,
  filter: Filter,
  menu: Menu,
  layoutLeft: PanelLeft,
  layoutRight: PanelRight,
  maximize: Maximize,
  map: MapIcon,
  mail: Mail,
  key: Key,
  shield: ShieldCheck,
  lock: Lock,
  gitBranch: GitBranch,
  zap: Zap,
  mapPin: MapPin,
  calendar: Calendar,
  github: Code,
  pencil: Pencil,
  award: Award,
  star: Star,
  message: MessageCircle,
  graduation: GraduationCap,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUpRight: ArrowUpRight,
  dot: Circle,
  ellipsis: Ellipsis,
  info: Info,
  alert: TriangleAlert,
  send: Send,
  folder: Folder,
  list: List,
  listOrdered: ListOrdered,
  table: Table,
  image: ImageIcon,
  bold: Bold,
  italic: Italic,
  sigma: Sigma,
  alignLeft: AlignLeft,
  database: Database,
  flag: Flag,
} satisfies Record<string, LucideIcon>

/** Icons that should be solid-filled instead of outlined. */
const filled: Partial<Record<keyof typeof icons, { fill: string; stroke?: string }>> = {
  play: { fill: 'currentColor' },
  star: { fill: 'currentColor' },
  dot: { fill: 'currentColor', stroke: 'none' },
}

export type IconName = keyof typeof icons

type IconProps = {
  name: IconName
  size?: number
  className?: string
  strokeWidth?: number
}

export function Icon({ name, size = 16, className, strokeWidth = 1.75 }: IconProps) {
  const Lucide = icons[name]
  if (!Lucide) return null
  const extra = filled[name]

  return (
    <Lucide
      size={size}
      strokeWidth={strokeWidth}
      className={className}
      aria-hidden="true"
      focusable="false"
      {...extra}
    />
  )
}